#+title: Readme

Этот проект предполагает запуск сугубо на моем телефоне: Xiaomi Redmi 4A(на базу MSM8917).

Нигде нет гарантии, что два телефона одной модели были сделаны полностью одинаково, поэтому на других телефонах той же модели этот проект может не работать.


* Что это?
Очередной пет-проект, который я скорее всего не завершу.

Вообще я хотел бы попробовать сделать posix совместимое микро ядро, да еще и на реальном железе.
Вот, правда, звучит это не совсем реалистично.

На текущий момент я хочу попробовать просто потыкать как устроено реальное железо, так как, хотя я и делал свое виртульное железо, с реальным на низком уровне я так и ни разу не работал.

* Если хочется попробовать
Для создания boot.img вам нужны:
 - android-tools (mkbootimg, fastboot)
 - aarch64-none-elf- компилятор и binutils
 - https://github.com/bkerler/edl

 #+begin_src shell
cd bootloader
make
fastboot boot build/boot.img
edl peek 0x90000000 0x2000 dump
 #+END_SRC

 в файле dump будут лежать логи загрузчика

* Откуда я беру документацию
К сожалению для большей(если не для всех) части устройств документация находится в закрытом доступе у qualcomm.

Поэтому приходится искать документацию в драйверах.

Дерево устройств можно найти либо в интернете, либо по пути `/sys/firmware/fdt` на работающей linux системе(android/postmarketos)

Драйвера для работы с этими устройствами я беру из 3 мест:
 - lk2nd
 - код ядра от xiaomi (https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/riva-n-oss)
 - код ядра от lineageos (https://github.com/LineageOS/android_kernel_xiaomi_msm8937) (да, msm8937)

В папке docs будут лежать файлы, в которых будет написано все об устройствах, для которых я нашел что-нибудь.
