#+title: MMU

* Регистры
** SCTLT_EL1
настройка что вообще есть в системе
с точки зрения MMU нас интересует только
| бит | что делает         |
|-----+-------------------|
|   0 | MMU               |
|   2 | Cache             |
|  12 | Instruction Cache |
** TTBR(1/0)_EL1
ссылка на корневую таблицу для трансляции адресов
у адреса есть неактивные биты(см. TCR_EL1)
TTBR1_EL1 используются когда все неактивные биты = 1
0 когда все = 0
биты 63:48 - ASID(номер по которому можно отличать память разных тасков без сброса кэша)
биты 47:0 - сам адрес таблицы(я надеюсь. возможно адрес - 47:x+1)
биты x:0 - должны быть = 0

`x is based on the value of TCR_EL1.T0SZ, the stage of translation, and the memory translation granule size. For instructions on how to calculate it, see the Arm Architecture Reference Manual Armv8, for Armv8-A architecture profile.`
** TODO TCR_EL1
настройка самого mmu
все что в названии имеет 0 относится к

| биты | название | значения или смысл                                                                         |
|------+---------+------------------------------------------------------------------------------------------|
|  5:0 | T0SZ    | размер самого адреса в битах = 64 - T0SZ, оставшиеся старшие биты неактивны(см. TTBR(0/1)_EL1) |
|    7 | EPD0    | если 1, то при промахе кэша tlb кидает исключение                                            |
|  9:8 | IRGN0   |                                                                                          |

(setq ispell-program-name "hunspell")
(setq ispell-dictionary "en_US,ru_RU")
(ispell-hunspell-add-multi-dic "en_US,ru_RU")

* Таблицы
по словам gemini `Размер полной таблицы на любом промежуточном уровне трансляции всегда равен размеру одной гранулы памяти`
